# 开发环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bomaos-shop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 日志配置
logging:
  level:
    com.bomaos: DEBUG
    com.baomidou.mybatisplus: DEBUG
